# This is a basic workflow to help you get started with Actions

name: MelodicBuildCI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ melodic-devel ]
  pull_request:
    branches: [ melodic-devel ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Setup ROS environment
      uses: ros-tooling/setup-ros@0.0.19

    - name: Test rosdep
      run: |
        mkdir -p $GITHUB_WORKSPACE/src
        mv $GITHUB_WORKSPACE/roborts_* $GITHUB_WORKSPACE/src
        cd $GITHUB_WORKSPACE
        rosdep update
        rosdep install -y --from-paths src --ignore-src --rosdistro melodic
        
    - name: Build
      run: |
        cd $GITHUB_WORKSPACE
        ls $GITHUB_WORKSPACE/src
        source /opt/ros/melodic/setup.bash
        catkin_make  
        
